version: '3'

services:
  app:
    build:
      context: .
    container_name: tasklist
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/tasklist?currentSchema=tasklist
      - SPRING_DATASOURCE_USERNAME=yaroslavyankov
      - SPRING_DATASOURCE_PASSWORD=postgres
    ports:
      - "9099:9099"

  db:
    image: postgres:15.1-alpine
    container_name: postgres
    environment:
      - POSTGRES_USER=yaroslavyankov
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=tasklist
    volumes:
      - ./src/main/resources/db-init:/docker-entrypoint-initdb.d