server:
  port: 9099
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/tasklist
    username: yaroslavyankov
    password: postgres
    driverClassName: org.postgresql.Driver
  sql:
    init:
      mode: always
      schema-locations: classpath:sql/schema.sql
#      data-locations: classpath:sql/demo_data.sql